# Generated by Django 4.0.6 on 2022-07-27 02:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0004_remove_post_likes_post_liked_alter_post_user_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=None, related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
